Repository LLMQuant/quant-wiki, pull requests merged in 2025-01, with the labels that each got.

#1 [workflow] Change the deploy branch to `master`.
  .github/workflows/deploy.yml
Labels: bug

#7 [Fix] Add the issue and pull request template.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/content-bug.yml
  .github/ISSUE_TEMPLATE/content-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/request-for-comment.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#8 [Fix] Modify the `pymdownx.betterem` to enbale bold syntax.
  mkdocs.yml
Labels: bug

#17 [Docs] Add the CONTRIBUTING guidance.
  .github/CONTRIBUTING.md
Labels: documentation

#22 [Docs] Add the special thanks.
  README.md
Labels: documentation

#23 feat(docs/library): 添加2024独家金融干货包
  docs/library/book/2024独家金融干货包/index.md
Labels: enhancement

#30 [Docs] Polish the contribution related docs.
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#31 [Docs] Fix the incorrect href.
  docs/contribute.md
Labels: documentation

#34 [Refactor] Refactor our templates.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .gitignore
Labels: documentation
